### PR TITLE
LATTester for linux kernel 5.1

### PR DESCRIPTION
**Pull request by heyhyohey**
I have modified lat.c and rep.c to make LATTester work on linux kernel 5.1.
I check again my codes and it works well.
Thank you.

### CODE REVIEW

**Comment by TheNetAdmin** [comment]
Looks good to me. Two suggestions:

1. You may miss the update for `bdev_dax_supported` in `lat.c` (you have it in `rep.c`)
2. We would like to maintain backward compatibility. So would you like to add `LINUX_VERSION_CODE` macro to guard the updates? Here is some reference code:
   - https://github.com/TheNetAdmin/LENS/blob/de32e0c0291f787998f0c3a2b9e02338ed9c5a4b/src/lat.c#L381-L392
   - https://github.com/TheNetAdmin/LENS/blob/de32e0c0291f787998f0c3a2b9e02338ed9c5a4b/src/lat.c#L428-L433

**Comment by heyhyohey** [comment]
By referencing attached links, I updated some code for backward compatibility.
I tested on both 4.13 and 5.1 version. and It works well on both.

**Comment by TheNetAdmin** [comment]
Great, thank you for the PR!

**Comment by heyhyohey** [comment]
Thank you!
I am happy to contribute to your code :)

**Pull request merged**
